x-flyway_template: &flyway_template
  image: flyway/flyway:latest
  depends_on:
    restaurant_db:
      condition: service_healthy

services:
  restaurant_db:
    build:
      context: .
    container_name: restaurant_db
    hostname: restaurant_db
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: luster
      POSTGRES_PASSWORD: luster
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  restaurant_db_migration:
    <<: *flyway_template
    container_name: restaurant_db_migration
    volumes:
      - ./sql:/flyway/sql
      - ./conf:/flyway/conf
    command: migrate
