name: 'Gradle Build Cache'
description: 'Gradle Build Cache'

inputs:
  cache-key:
    description: 'Cache Key'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches/build-cache-*
          ~/.gradle/caches/[0-9]*.*
          .gradle
        key: ${{ runner.os }}-gradle-build-${{ github.workflow }}-${{ steps.cache-key.outputs.week }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-gradle-build-${{ github.workflow }}-${{ steps.cache-key.outputs.week }}-