---
spring:
  devtools:
    add-properties: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: luster
    password: luster

server:
  port: 8080

logging:
  level:
    jp:
      kukv: debug

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
