name: on-pull-request-module-settings

on:
  pull_request:
    paths-ignore:
      - 'docker/**'
      - '.gitignore'
      - '**.md'
      - 'renovate.json'

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      cache-key: ${{ steps.weekly.cache-key.outputs.key }}
    steps:
      - id: weekly-cache-key
        run: echo "key=$(TZ=Asia/Tokyo date +%W)" >> $GITHUB_OUTPUT

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Gradle Wrapper Cache
        uses: ./.github/actions/gradle-cache-strategy/wrapper-cache

      - name: Gradle Dependencies Cache
        uses: ./.github/actions/gradle-cache-strategy/dependencies-cache
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}

      - name: Gradle Build Cache
        uses: ./.github/actions/gradle-cache-strategy/build-cache
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Grant Execute Permission to gradlew
        run: chmod +x gradlew

      - name: Check with Gradle
        run: ./gradlew check